learning_log/urls.py
from django.contrib import admin
from django.urls import include, path

# app_name = 'learning_logs'
urlpatterns = [
    path('admin/', admin.site.urls),
    # path('users/', include('users.urls', namespace = 'users')),
    path('', include('learning_logs.urls', namespace = 'learning_logs'))    
]

learning_logs/urls.py
"""Определяет схемы URL для learning_logs."""
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
 # Домашняя страница
	 path('', views.index, name='index'),
 # Страница со списком тем   
     path(r'topics/', views.topics, name='topics'),
 # Страница с подробной информацией по отдельной теме
	 path(r'topics/(<topic_id>\d+)/', views.topic, name='topic'),
 # Страница для добавления новой темы
	 path(r'new_topic/', views.new_topic, name = 'new_topic'),
 # Страница для добавления новой записи
	 path(r'new_entry/(<topic_id>\d+)/', views.new_entry, name = 'new_entry'),
 # Страница для редактирования записи
	 path(r'edit_entry/(<entry_id>\d+)/', views.edit_entry, name = 'edit_entry'),
     path('login/',  LoginView.as_view(template_name='login.html'), name='login'),
     path('logout/', LogoutView.as_view(template_name='logout.html'), name='logout'),
     path('register/', views.register, name='register'),
]

users/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
 
from . import views

urlpatterns = [
    # Страница входа
    path('login/',  LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User,on_delete=models.CASCADE)
    def __str__(self):
        return self.text
    
class Entry(models.Model):
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Возвращает строковое представление модели."""
        if len(self.text)>50:
            return self.text[:50] + "..."
        else:
            return self.text

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):

    class Meta():
        model = Topic
        fields = ['text']
        labels = {'text': ''} 

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required

def index(request):
    """Домашняя страница приложения Learning Log"""
    return render(request,'learning_logs/index.html')

@login_required
def topics(request):
    """Выводит список тем"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """Выводит одну тему и все ее записи."""
    topic = Topic.objects.get(id=topic_id)
    # Проверка того, что тема принадлежит текущему пользователю.
    check_owner(topic, request)
    # if topic.owner != request.user:
    #     raise Http404 
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    print(topic, entries)
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """Определяет новую тему."""
    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        form = TopicForm()
    else:
        # Отправлены данные POST; обработать данные.
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
        
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Добавляет новую запись по конкретной теме."""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        form = EntryForm()
    else:
        # Отправлены данные POST; обработать данные.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            check_owner(topic,request)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))
        
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)    

def check_owner(topic, request):
    if topic.owner != request.user:
        raise Http404

@login_required
def edit_entry(request, entry_id):
    """Редактирует существующую запись."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        # Исходный запрос; форма заполняется данными текущей записи.
        form = EntryForm(instance=entry)
    else:
        # Отправка данных POST; обработать данные.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)   
        
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

def register(request):
    """Регистрирует нового пользователя."""
    if request.method != 'POST':
        # Display blank registration form.   
        form = UserCreationForm()
    else:
        # Обработка заполненной формы.
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # Выполнение входа и перенаправление на домашнюю страницу.
            authenticated_user = authenticate(username=new_user.username,
                password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))
    context = {'form': form}
    return render(request, 'learning_logs/register.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
# from django.contrib.auth.views import logout
from django.urls import reverse

# def logot_view(request):
#     """Завершает сеанс работы с приложением."""
#     logout(request)
#     return HttpResponseRedirect(reverse('learning_logs:index'))
# Create your views here.

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <title>Learning Log</title>
   {% bootstrap_css %}
   {% bootstrap_javascript %}
</head>
<body>
    <!-- Статическая навигационная панель -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
            </button>
                     <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
                         Learning Log</a>
                   </div>
                   <div id="navbar" class="navbar-collapse collapse">
                     <ul class="nav navbar-nav">
                       <li><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
                       <li><a href="{% url 'learning_logs:topics' %}">Topics1</a></li>
                       <li><a href="{% url 'learning_logs:topics' %}">Topics2</a></li>
                     </ul>
                     <ul class="nav navbar-nav navbar-right">
                       {% if user.is_authenticated %}
                         <li><a>Hello, {{ user.username }}.</a></li>
                         <form action="{% url 'learning_logs:logout' %}" method="post">
                            {% csrf_token %} 
                            <button type="submit">Logout</button>
                        </form>
                        <!-- <a href="{% url 'learning_logs:logout' %}"> log out </a> -->
                       {% else %}
                         <li><a href="{% url 'learning_logs:register' %}">register</a></li>
                         <li><a href="{% url 'learning_logs:login' %}">log in</a></li>
                       {% endif %}
                      </ul>
                   </div><!--/.nav-collapse -->
                 </div>
               </nav>
               <div class="container">
                <div class="page-header">
                  {% block header %}{% endblock header %}
                </div>
                <div>
                  {% block content %}{% endblock content %}
                </div>
              </div> <!-- /container -->
</body>
</html>

learning_logs/templates/learning_logs/base_old.html
<p>
    <a href="{% url 'learning_logs:index' %}"> Learning Log</a> -
    <a href="{% url 'learning_logs:topics' %}"> Topics</a>
    {% if user.is_authenticated %}
    Hello, {{ user.username }}
    <form action="{% url 'learning_logs:logout' %}" method="post">
        {% csrf_token %} 
        <button type="submit">Logout</button>
    </form>
    <!-- <a href="{% url 'learning_logs:logout' %}"> log out </a> -->
    {% else %}
    <a href="{% url 'learning_logs:register' %}">register</a> 
    <a href="{% url 'learning_logs:login' %}"> log in </a>
    {% endif %} 
</p>
{% block content %}{% endblock content %}

LfndkfndHSD^38

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block content %}
<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
<p>Edit entry:</p>
<form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name="submit">save changes</button>
    {% endbuttons %}
</form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
{% block header %}
<div class='jumbotron'>
    <h1>Track your learning.</h1>        
</div>
{% endblock header %}
{% block content %}
<h2>
    <a href="{% url 'learning_logs:register' %}">Register an account</a> to make
    your own Learning Log, and list the topics you're learning about.
  </h2>
  <h2>
    Whenever you learn something new about a topic, make an entry 
    summarizing what you've learned.
</h2>
{% endblock content %}

learning_logs/templates/learning_logs/logout.html
{% extends "learning_logs/base.html" %}

{% block  content %}
<p>You are logged out</p>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
<h2>Add a new entry</h2>
{% endblock header %}

{% block content %}
<p><a href="{% url 'learning_logs:topic' topic.id %}">{{  topic  }}</a></p>
<p>Add a new entry:</p>
     <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post' class="form">
     {% csrf_token %}
     {% bootstrap_form form %}
     {% buttons %}
     <button name='submit'>add entry</button>
     {% endbuttons %}
 </form>
 
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Add a new topic:</h2>
{% endblock header %}

{% block content %}
<form action="{% url 'learning_logs:new_topic' %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name="submit" class="btn btn-primary">add topic</button>
    {% endbuttons %}
</form>

{% endblock content %}

learning_logs/templates/learning_logs/register.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block header %}
<h2>Register a new account</h2>
{% endblock header %}
{% block content %}
 <form method="post" action="{% url 'learning_logs:register' %}" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
  <button name="submit">register</button>
  {% endbuttons %}
  <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
</form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
{% block header %}
  <h2>{{ topic }}</h2>
{% endblock header %}
{% block content %}
	 <p>Topic: {{ topic }}</p>
 <p>Entries:</p>
 <p>
	<a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
</p>
	<ul>
	 {% for entry in entries %}
	<div class="panel panel-default">
		<div class="panel-heading">
		  <h3>
			{{ entry.date_added|date:'M d, Y H:i' }}
			<small>
			  <a href="{% url 'learning_logs:edit_entry' entry.id %}">
				edit entry</a>
			</small>
        </h3>
        </div>
      <div class="panel-body">
        {{ entry.text|linebreaks }}
      </div>
    </div> <!-- panel -->
	 {% empty %}
 <li>
 There are no entries for this topic yet.
 </li>
 {% endfor %}
 </ul>
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% block header %}
  <h1>Topics</h1>
{% endblock header %}
{% block content %}
<p> Topics </p>
<ul>
    {% for topic in topics %}
    <li>
        <h3><a href = "{% url 'learning_logs:topic' topic.id %}">{{ topic}}</a></h3>        
        </a></li>
    {% empty %}
        <li>No topics have been added yet.</li>
    {% endfor %}
</ul>

<h3><a href="{% url 'learning_logs:new_topic' %}">Add a new topic:</a></h3>

{% endblock content %}

learning_logs/templates/login.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block header %}
<h2>Log in to your account.</h2>
{% endblock header %}
{% block  content %}
<form method="post" action="{% url 'learning_logs:login' %}" class="form">
{% csrf_token %}    
{% bootstrap_form form %}
{% buttons %}
 <button name="submit" class="btn btn-primary">log in</button>
{% endbuttons %}
<input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
</form>

{% endblock content %}

users/templates/base.html
<p>
    <a href="{% url 'learning_logs:index' %}"> Learning Log</a> -
    <a href="{% url 'learning_logs:topics' %}"> Topics</a>
    {% if user.is_authenticated %}
    Hello, {{ user.username }}
    <a href="{% url 'users:logout' %}"> log out </a>
    {% else %}
    <a href="{% url 'users:login' %}"> log in </a>
    {% endif %} 
</p>
{% block content %}{% endblock content %}

users/templates/index.html
{% extends "learning_logs/base.html" %}

{% block content %}
<p>Learning Log helps you keep track of your learning, for any topic you're
learning about.</p>
{% endblock content %}

users/templates/login.html
{% extends "learning_logs/base.html" %}
{% block  content %}
{% if form.errors %}
<p>Your username or password didn't match </p>
{% endif %}

<form method="post" action="{% url 'users:login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit"> log in </button>
    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
</form>

{% endblock content %}